### ISSUE TITLE
Problem clicking the  icon

### ISSUE THREAD

**Issue by javierdac** [fateh999/react-native-paper-dropdown#1]
If you click the icon you can access to the TextField and the dropdown is not being displayed.

**Comment by fateh999** [comment]
`
        <DropDown
          label={'Gender'}
          mode={'outlined'}
          visible={showDropDown}
          showDropDown={() => setShowDropDown(true)}
          onDismiss={() => setShowDropDown(false)}
          value={gender}
          setValue={setGender}
          list={genderList}
          inputProps={{
            right: <TextInput.Icon name={'menu-down'} />,
          }}
        />
        `
