### ISSUE TITLE
How do I get rid of these purple bars at top and bottom of each list item?

### ISSUE THREAD

**Issue by inferno080** [fateh999/react-native-paper-dropdown#103]
![image](https://github.com/fateh999/react-native-paper-dropdown/assets/67534207/12e4bcef-71bd-45c3-8a88-e4af352c662a)

**Comment by jbierfeldt** [comment]
You need to change elevation.level2 in your theme colors.

```
export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    elevation: {
      level2: "#ffffff"
    }
  },
};
```

**Comment by Acarvajal904** [comment]
> You need to change elevation.level2 in your theme colors.
> 
> ```
> export const theme = {
>   ...DefaultTheme,
>   colors: {
>     ...DefaultTheme.colors,
>     elevation: {
>       level2: "#ffffff"
>     }
>   },
> };
> ```

but not only change the background color, what about not have them ?
