### ISSUE TITLE
How to change background color?

### ISSUE THREAD

**Issue by sanket-solulab** [fateh999/react-native-paper-dropdown#12]

**Comment by rumwerfer** [comment]
Hi, I was just wondering the same. It uses the `surface` color, so simply change that in your theme.

**Comment by fateh999** [comment]
There are new props in v1.0.3 dropDownStyle & dropDownItemStyle that can help with your case

**Comment by sanket-solulab** [comment]
Thanks 👍

**Comment by tobecwb** [comment]
It's not possible to change the background color of a "closed" dropdown, even with dropDownStyle and dropDownItemStyle.
The surface color only works with background of the "menu" (after click on down arrow of dropdown).

**Comment by samuelvisscher** [comment]
Thanks @tobecwb that's very unfortunate. Means I will have to look for another library.

**Comment by bondythegreat** [comment]
since it uses paper's color.background:

`const myTheme = useTheme()
  const customTheme = {
    ...myTheme,
    colors: {
      ...myTheme.colors,
      background: '#ffffff', // white background when closed
    },
  }`
  
  `<Dropdown theme={customTheme}`

**Comment by muneerpuri** [comment]
this code worked for me to change background color of the dropdown. -react native paper dropdown
 ```
    <DropDown
      // label={'P'}
      mode={'outlined'}
      visible={showMobileDropDOwn}
      showDropDown={() => setShowMobileDropDOwn(true)}
      onDismiss={() => setShowMobileDropDOwn(false)}
      setValue={setPhoneCountry}
      value={phoneCountry}
      list={codes}
      inputProps={{
        style:{
          width:90,
          backgroundColor: 'rgb(252,243,207)',
          height:20
        }
      }}
    />
 ```

**Comment by abdurrahman6489** [comment]
when mode is changed to mode={'outlined'} in the props, background color is set to almost white, but i tried other ways, but background color not changing, using version ^2.3.1
