### ISSUE TITLE
How to set the height of Dropdown Items' container

### ISSUE THREAD

**Issue by jgudo** [fateh999/react-native-paper-dropdown#15]
Is it possible to set a height to the container of the dropdown's items? 
I've tried setting it on a ```SafeAreaView``` which wraps the ```DropDown``` components but the Dropdown ended up disappearing. 

![Screenshot_20210603-122342_Pelco I Meter Reading](https://user-images.githubusercontent.com/30772059/120587215-8b240000-c467-11eb-8bec-1b512a335492.jpg)

**Comment by fateh999** [comment]
There are new props in v1.0.3 dropDownStyle & dropDownItemStyle that can help with your case
