### ISSUE TITLE
Any way to also focus on TextInput when Dropdown is focused?

### ISSUE THREAD

**Issue by marcoshevaristo** [fateh999/react-native-paper-dropdown#17]
I see that you use the react-native-paper TextInput to render the input field, but the TextInput (outlined) has a feature that changes the border color based on the theme color on focus. Is there any way we can achieve the same behavior with this Dropdown component? I tried forking it to call the TextInput "focus" method manually, but I couldn't build it to test it.

**Comment by fateh999** [comment]
Will be adding it by default in next update

**Comment by fateh999** [comment]
Actually focussing on it through ref was opening up the keyboard but input border was highlighted with primary theme color, which is not the correct behaviour for a dropdown. So dropping this
