### ISSUE TITLE
Is there a way to change component height?

### ISSUE THREAD

**Issue by dcanora** [fateh999/react-native-paper-dropdown#19]
Sorry if I'm missing it, but is there a way to change the base component height?  TIA.

**Comment by fateh999** [comment]
Did you try modifying style using the dropDownStyle prop

**Comment by dcanora** [comment]
`dropDownStyle={{height: XX}}` changed the height of the dropdown that's displayed when clicked, not the base component itself. Is there something else I can try? 

Thanks!

**Comment by Parth15Ordex** [comment]
@dcanora 
you can do it using inputProps like below

`inputProps={{style : {height : 40}}}`

**Comment by dcanora** [comment]
@Parth15Ordex  - Ah! That did it. Thank you very much!
