### ISSUE TITLE
Background shadow issue on click

### ISSUE THREAD

**Issue by Parth15Ordex** [fateh999/react-native-paper-dropdown#21]
When we click on dropdown, there is a background shadow effect appears.
Is there any way to remove it?

**Reference Image :** 

![Screenshot 2021-07-09 at 10 58 17 AM](https://user-images.githubusercontent.com/48586479/125030221-5f201e00-e0a8-11eb-8cae-cd945c375953.png)

**Comment by fateh999** [comment]
@Parth15Ordex can you provide which react-native-version are you on?

**Comment by Parth15Ordex** [comment]
@fateh999 
It's **0.64.0**

**Comment by fateh999** [comment]
Ok will test with that version and let you know.

**Comment by launcherx** [comment]
I have the same problem in iOS simulator (not tested on android)

Issue is with `TouchableRipple` for some reason it's not working and going to fallback mode if not supported (Based on react-native-paper `TouchableRipple` documentation).

Is it possible to add prop which allow to replace `TouchableRipple` with `TouchableOpacity`?

**Comment by MadhavNasit** [comment]
> I have the same problem in iOS simulator (not tested on android)
> 
> Issue is with `TouchableRipple` for some reason it's not working and going to fallback mode if not supported (Based on react-native-paper `TouchableRipple` documentation).
> 
> Is it possible to add prop which allow to replace `TouchableRipple` with `TouchableOpacity`?

Facing same issue, I can be solved by passing props into touchableRipple, we can change color of TouchableRipple to 'transparent'.
