### ISSUE TITLE
dropDownItemTextStyle problem on IOS

### ISSUE THREAD

**Issue by yafetHamouda** [fateh999/react-native-paper-dropdown#23]
dropDownItemTextStyle and dropDownItemSelectedTextStyle props are working fine on android but not on IOS.

**Comment by yafetHamouda** [comment]
<DropDown
        visible={visible}
        showDropDown={() => setVisible(true)}
        onDismiss={() => setVisible(false)}
        value={value || dropdownAssets[0]?.value}
        setValue={setValue}
        list={dropdownAssets}
        inputProps={{
          right: <TextInput.Icon name={'menu-down'} color={Colors.grey400} />,
          style: [styles.dropdownInput, {fontSize: windowWidth > 380 ? 12 : 11}],
          underlineColor: 'transparent',
        }}
        theme={{
          ...DefaultTheme,
          colors: {
            ...DefaultTheme.colors,
            text: PALETTE.darkBlue,
          },
        }}
        activeColor={PALETTE.darkBlue}
        dropDownItemTextStyle={{color: 'red'}}
        dropDownItemSelectedTextStyle={{color: 'red'}}
      />

<img width="148" alt="Screen Shot 2021-07-14 at 6 59 12 PM" src="https://user-images.githubusercontent.com/2091056/125670328-048c0e63-9873-45fe-be75-9fd7b8b6acc5.png">

dropDownItemTextStyle and dropDownItemSelectedTextStyle not taking effect.

**Comment by fateh999** [comment]
Ok will test with your code sample

**Comment by fateh999** [comment]
Fixed
