### ISSUE TITLE
Feature Request: Can you add a multi select view ?

### ISSUE THREAD

**Issue by srivastavaanurag79** [fateh999/react-native-paper-dropdown#25]
[For Reference: https://www.npmjs.com/package/react-native-multi-selectbox ](https://www.npmjs.com/package/react-native-multi-selectbox)

Feature Request:
There aren't any material multi-select for react native using react native paper.

**Comment by fateh999** [comment]
Sounds good, will be releasing next major release with this.

**Comment by srivastavaanurag79** [comment]
with a search bar, or can you help me build it i am stuck at handling state of the dynamic checkbox, i am using checkbox to select multiple data when i console log the state of checkboxes are changed but it isn't updating the checkbox icon when i reload the app it shows the updated view

**Comment by fateh999** [comment]
![IMG_20210724_103836](https://user-images.githubusercontent.com/16474502/126858072-bb8566ca-570b-4f6f-acf1-8beca875ccc8.jpg)

I am thinking implementation like this will be better, the above image is from react material ui.

**Comment by srivastavaanurag79** [comment]
yes i am trying to implement the same thing inside the react native paper dialog. but the thing is that, when i click the checkboxes it does update the array which holds the checkbox's checked state, i can see the log in the terminal, but it isn't updating the checkbox icon, if i save my code metro hot reloads and i can then see the updated checkbox icons.
<img width="174" alt="Screenshot 2021-07-24 104647" src="https://user-images.githubusercontent.com/24560090/126858211-67cdc969-d622-4ec6-beca-34ca5eea8ff4.png">

**Comment by srivastavaanurag79** [comment]
Any idea how to custom template or React Native Paper Chip inside Textinput ???
<img width="159" alt="Screenshot 2021-07-24 174352" src="https://user-images.githubusercontent.com/24560090/126868109-d3d10438-1b51-43bf-8b6f-aad18aac1315.png">
<img width="152" alt="Screenshot 2021-07-24 174523" src="https://user-images.githubusercontent.com/24560090/126868111-98d57b5e-244e-41e0-8b43-2086afa17fe9.png">

This looks very raw, adding selected elements as chip would make it complete

**Comment by fateh999** [comment]
For now will be displaying comma separated TextInput.
