### ISSUE TITLE
How to customize the 'menu-up' and 'menu-down' icon font?

### ISSUE THREAD

**Issue by busterbogheart** [fateh999/react-native-paper-dropdown#27]

**Comment by busterbogheart** [comment]
Would this be done on the vector-icons side or is it possible to specify within the dropdown  module?

**Comment by mdfateh** [comment]
You can update by passing  right: <TextInput.Icon name={visible ? "menu-up" : "menu-down"} /> in inputProps to the component.

**Comment by mdfateh** [comment]
You can look up the props of react-native-paper TextInput for more options.
