### ISSUE TITLE
EventEmitter.removeListener('change', ...): Method has been deprecated

### ISSUE THREAD

**Issue by everestster** [fateh999/react-native-paper-dropdown#34]
I'm getting the following warning.
 WARN  EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

"react-native": "^0.65.1",
"react-native-paper": "^4.9.2",
"react-native-paper-dropdown": "^1.0.7",

Dropdown doesn't expand react native's Modal too.

**Comment by DiegoBM** [comment]
Getting the same warning message

**Comment by andrei0807** [comment]
Please fix this error asap

**Comment by oguilb** [comment]
I think that problem is in Menu componant of Paper
