### ISSUE TITLE
Unable to scroll dropDownContainer on Android

### ISSUE THREAD

**Issue by yutanakano** [fateh999/react-native-paper-dropdown#36]
It works fine on iOS, but as the title says, I can't scroll dropDownContainer on Android.

**Comment by Raheel1258** [comment]
> 
In my case it scrolls normally. But when dropdownContainer appears within a scrollview, it does not scroll.

**Comment by marianvd666** [comment]
listMode='SCROLLVIEW'              write this inside the dropdownpicker component
