### ISSUE TITLE
Dropdown menu blank Due to color: undefined

### ISSUE THREAD

**Issue by cybersasi** [fateh999/react-native-paper-dropdown#4]
The dropdown menu show nothing because the color is undefined

![Screenshot 2020-10-04 at 3 52 17 PM](https://user-images.githubusercontent.com/3701196/95010143-99f8af80-0659-11eb-9898-5ba9a6d62dd6.png)

![Screenshot_20201004-153631](https://user-images.githubusercontent.com/3701196/95010120-70d81f00-0659-11eb-936d-cd14ea6a0fa3.jpg)

After I change the color to : `(theme || activeTheme).colors.text ` the menu show out 

![Screenshot_20201004-154911](https://user-images.githubusercontent.com/3701196/95010163-bb599b80-0659-11eb-9f10-c52ec3de4bfd.jpg)

**Comment by fahad39** [comment]
give more simple example

**Comment by adamgajzlerowicz** [comment]
I think it's working on ios for some reason. I am experiencing this on Android only.

**Comment by sarthak216-blr** [comment]
> The dropdown menu show nothing because the color is undefined
> 
> ![Screenshot 2020-10-04 at 3 52 17 PM](https://user-images.githubusercontent.com/3701196/95010143-99f8af80-0659-11eb-9898-5ba9a6d62dd6.png)
> 
> ![Screenshot_20201004-153631](https://user-images.githubusercontent.com/3701196/95010120-70d81f00-0659-11eb-936d-cd14ea6a0fa3.jpg)
> 
> After I change the color to : `(theme || activeTheme).colors.text ` the menu show out
> 
> ![Screenshot_20201004-154911](https://user-images.githubusercontent.com/3701196/95010163-bb599b80-0659-11eb-9f10-c52ec3de4bfd.jpg)

Same issue

**Comment by adamgajzlerowicz** [comment]
Considering 100 lines in the source code I just copied it directly to my components dir with the fix applied :)
