### ISSUE TITLE
dropdown conatiner  going outside of screen

### ISSUE THREAD

**Issue by shashank1501** [fateh999/react-native-paper-dropdown#41]
If the dropdown is at bottom of the screen dropdown items are going outside of the screen.
expected behavior: dropdown container moves up if the dropdown is at bottom of the screen.

![Screenshot_1632806135](https://user-images.githubusercontent.com/60471796/135027717-2ccff048-3166-4445-862b-2eb198b83bfb.png)
![Screenshot_1632806295](https://user-images.githubusercontent.com/60471796/135027728-c7b63219-f9d6-42d7-b13d-d2d9a30c1573.png)

**Comment by FelipeACP** [comment]
Solved this by setting dropDownContainerHeight like so

` dropDownContainerHeight={Dimensions.get("window").height * 0.4}`

**Comment by bombillazo** [comment]
Any update on this?
