### ISSUE TITLE
Weird ripple behaviour

### ISSUE THREAD

**Issue by AndrewIsBest69** [fateh999/react-native-paper-dropdown#50]
When using the dropdown menu in both outlined and flat mode, the ripple effect is only visible on the background part of the Dropdown component (even though with flat it's visible only on the corner, but still, quite irritating)
![Screenshot_1637780804](https://user-images.githubusercontent.com/47299500/143299637-988288be-dfcf-4aeb-8904-75c0ab644df9.png)
![Screenshot_1637780810](https://user-images.githubusercontent.com/47299500/143299646-bea1f7d7-a682-4461-96c6-699aa3fedaff.png)

![Screenshot_1637781027](https://user-images.githubusercontent.com/47299500/143299815-c74e75a9-bf6c-4d0b-8804-fc1afe329903.png)
![Screenshot_1637781032](https://user-images.githubusercontent.com/47299500/143299824-5e2b1866-66bb-41b1-93fc-e3ff19a1c0ad.png)

My dependencies and their versions:
`  
"@react-native-async-storage/async-storage": "^1.15.11",
"@react-navigation/drawer": "^6.1.8",
"@react-navigation/native": "^6.0.6",
"base-64": "^1.0.0",
"date-and-time": "^2.0.1",
"react": "17.0.2",
"react-native": "0.66.2",
"react-native-gesture-handler": "^1.10.3",
"react-native-paper": "^4.10.0",
"react-native-paper-dropdown": "^1.0.7",
"react-native-reanimated": "^2.2.4",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "^3.9.0",
"react-native-uuid": "^2.0.1",
"react-native-vector-icons": "^9.0.0",
"utf8": "^3.0.0"
`

**Comment by sarath-dataequinox** [comment]
Any solution?

**Comment by sambeetsahu** [comment]
How you fixed it

**Comment by ManishAdglobal360** [comment]
please share solution
