### ISSUE TITLE
Showing drop down in wrong area

### ISSUE THREAD

**Issue by rsahu34** [fateh999/react-native-paper-dropdown#55]
![Simulator Screen Shot - iPhone 11 - 2022-02-17 at 13 35 17](https://user-images.githubusercontent.com/10787146/154432213-e08bc464-38fc-4223-b113-567fb7731c35.png)

**Comment by flavioftkode** [comment]
Edit the file DropDown.js, set line 62 to ' marginTop: inputLayout?.height - 68,' fixes the problem for now

**Comment by rsahu34** [comment]
Thank you so much, it working now

**Comment by rie-kumar** [comment]
So, modifying the marginTop does help improve the location, but it causes each device to display it differently
