### ISSUE TITLE
Is there any way to change the background colour?

### ISSUE THREAD

**Issue by shubhadeep-kartbite** [fateh999/react-native-paper-dropdown#68]
I want to make the backgroud color to white

![Screenshot 2022-05-27 at 01 31 07](https://user-images.githubusercontent.com/87764686/170568766-508a9da8-9d01-47c9-a804-39f544d5ea4a.png)

**Comment by vikramkaldoke** [comment]
yes! you  can change background color using inputProps.
  inputProps={{
              style: {
                borderColor: color.tertiary.pink_100,
                backgroundColor: color.tertiary.aquaGreen2,
                height: 56,
              },
              underlineColor: color.tertiary.darkAquaGreen,
              activeOutlineColor: color.primary.black,
            }}

**Comment by Koxx3** [comment]
hello,
I am looking to do the same.
I use the "outlined" mode, backgroundColor works... but borderColor doesn't. any idea ?
thanks

**Comment by Yennnful** [comment]
> yes! you can change background color using inputProps. inputProps={{ style: { borderColor: color.tertiary.pink_100, backgroundColor: color.tertiary.aquaGreen2, height: 56, }, underlineColor: color.tertiary.darkAquaGreen, activeOutlineColor: color.primary.black, }}

@Koxx3 just like @vikramkaldoke said, use inputProps
try putting outlineColor instead of active outline color
something like:
  inputProps={{
        style: {
            backgroundColor: color.tertiary.aquaGreen2,
            height: 56,
        },
        outlineColor: 'green' // you need this
    }}
