### ISSUE TITLE
Demo image in README.md

### ISSUE THREAD

**Issue by rockingrohit9639** [fateh999/react-native-paper-dropdown#70]
Hey there, 
It is a good idea to have a demo image in the README.md file. It gives the user a clear view of what he/she gonna get when he/she installs the package.
If you allow me, I can add an image showing how the dropdown looks.

**Comment by badsyntax** [comment]
fyi there is a demo image in the readme, it just takes forever to load because [it's 40mb](https://github.com/fateh999/react-native-paper-dropdown/raw/master/Demo.gif)
