### ISSUE TITLE
when click on dropdown its not opening

### ISSUE THREAD

**Issue by PradeepKpi** [fateh999/react-native-paper-dropdown#72]
When we click on the dropdown the list is not showing

**Comment by bombillazo** [comment]
You need a state variable that controls the dropdown visibility. The component does not take care of that automatically.

```
cosnt [visible, setVisible] = useState(false);

<RNPDropDown
  visible={visible}
  ...
/>

```

**Comment by NaveenKumarMFRL** [comment]
> You need a state variable that controls the dropdown visibility. The component does not take care of that automatically.
> 
> ```js
> cosnt [visible, setVisible] = useState(false);
> 
> <RNPDropDown
>   visible={visible}
>   ...
> />
> ```

i have using visible props but also its not showing

**Comment by angelxmoreno** [comment]
@NaveenKumarMFRLshowing code helps.
@bombillazo This is what I have and still nothing changes
```ts
<DropDown
    label={"Language"}
    mode={"outlined"}
    visible={true}
    showDropDown={() => setShowDropDown(true)}
    onDismiss={() => setShowDropDown(false)}
    value={colors}
    setValue={setColors}
    list={colorList}
/>
```
I am using:
```
"react-native-paper": "^5.8.0",
"react-native-paper-dropdown": "^1.0.7",
```

**Comment by bombillazo** [comment]
hey @angelxmoreno I'm no longer using RN, but perhaps it is due to incompatibility with the latest RNP versions since this component has not been updated in 2 years and RNP has been changing their components implementations.

**Comment by angelxmoreno** [comment]
thanks for the assist @bombillazo . I'll reach out to @fateh999 and see if he needs help with the current PRs
