### ISSUE TITLE
v2.0 is in the works and I would incorporate all the requested features, alongside maintaining the v1+

### ISSUE THREAD

**Issue by fateh999** [fateh999/react-native-paper-dropdown#80]

**Comment by SushritPasupuleti** [comment]
Material You support that's coming with v5 (currently in RC) would be nice!

**Comment by SushritPasupuleti** [comment]
Also a way to support multiple value input would be nice like the way MUI offers ([reference](https://mui.com/material-ui/react-autocomplete/#fixed-options))

**Comment by 1010nishant** [comment]
Hi brother @fateh999 are you still working on this v2?
or this repo is not maintained anymore?

**Comment by fateh-onloop** [comment]
Yeah @1010nishant currently i am not able to give time to this due to my work. But maybe in future once i am free will revisit this.

**Comment by fateh999** [comment]
Yeah @1010nishant currently i am not able to give time to this due to my work. But maybe in future once i am free will revisit this.

**Comment by 1010nishant** [comment]
no issue. Although this library is open source, if I fork it, update it and publish it on npm, would I need any kind of licensing from you?

**Comment by fateh999** [comment]
@1010nishant no issue you can create and publish your npm package from the fork

**Comment by 1010nishant** [comment]
ok thanks for responding brother.

**Comment by fateh999** [comment]
v2.0.0 is now released with a full refactor. Docs are WIP
