### ISSUE TITLE
Dropdown appears behind modal

### ISSUE THREAD

**Issue by rickwillcox** [fateh999/react-native-paper-dropdown#84]
When You use this dropdown on a modal the actual dropdown part appears behind the modal itself. Ive tried setting every single area possible that I can think of zIndex to a high value but nothing every changed. Ive used inspect element and changed the zindex there as well and it doesnt change anything.

In the below gif im changing the position of the dropdown in the dev tools styles editor, just to show that I do indeed have the correct container. 

https://user-images.githubusercontent.com/53924507/196331803-eddce48a-0387-4834-aa21-620f451ea6c6.mp4

Any ideas?

**Comment by Ghoral** [comment]
Same issue..it works with this modal `https://www.npmjs.com/package/@gorhom/bottom-sheet` but it is not what we need.
It should work with normal modals as well.

**Comment by Blaxzter** [comment]
I was able to fix this problem when i put [Portal.Host](https://callstack.github.io/react-native-paper/docs/components/Portal/PortalHost/) around the content of the modal content.
