### ISSUE TITLE
dropdown icon is not visible in latest version of paper [fix included]

### ISSUE THREAD

**Issue by rodrigoAbril** [fateh999/react-native-paper-dropdown#91]
in line [164 of DropDown.tsx](https://github.com/fateh999/react-native-paper-dropdown/blob/master/src/DropDown.tsx#L164)

to fix change  attribute `name` to `icon` as seen in https://callstack.github.io/react-native-paper/text-input-icon.html

**Comment by RiedelNicolas** [comment]
Thanks a lot @otskarli !

**Comment by fateh999** [comment]
Should be fixed in latest release v2.0.3, did a full refactor of library so docs are in WIP, meanwhile you can check the example folder for demo code.
